# Generated by Django 3.2.6 on 2021-09-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myFirstApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFirstApp.stock')),
                ('buyPrice', models.FloatField(default=-1)),
                ('amount', models.FloatField()),
                ('close', models.FloatField(default=-1)),
                ('changeProfit', models.FloatField(default=-1)),
                ('profit', models.FloatField(default=-1)),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            bases=('myFirstApp.stock',),
        ),
        migrations.CreateModel(
            name='StocksProtfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('value', models.FloatField(default=0)),
                ('changePer', models.FloatField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('listOfStock', models.CharField(default='[]', max_length=2000000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
