# Generated by Django 3.2.6 on 2021-09-11 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_auto_20210911_1337'),
        ('virtualMarket', '0002_rename_stocksportfolio_stocksprotfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFirstApp.stock')),
                ('buyPrice', models.FloatField()),
                ('amount', models.FloatField()),
                ('close', models.FloatField(default=-1)),
                ('changeProfit', models.FloatField(default=-1)),
                ('profit', models.FloatField(default=-1)),
                ('time', models.DateField(default=datetime.datetime(2021, 9, 11, 14, 48, 15, 687610), verbose_name='Date')),
            ],
            bases=('myFirstApp.stock',),
        ),
    ]
